name: AI Short Video Generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"   # runs daily at 09:00 UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI video script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: |
          mkdir -p output
          python ai_short_video.py --topic "Engineering Marvels Across the World" --n_images 3 --use_eleven

      - name: Upload artifact (video)
        uses: actions/upload-artifact@v4
        with:
          name: ai-short-video-output
          path: output/*.mp4
